#!/bin/sh
#
# @name Rocket SITLv1
#

. ${R}etc/init.d/rc.fw_defaults

param set-default EKF2_MAG_ACCLIM 0
param set-default EKF2_MAG_YAWLIM 0
param set-default FD_FAIL_P 0
param set-default FD_FAIL_R 0

param set-default FW_LND_AIRSPD_SC 1
param set-default FW_LND_ANG 8
param set-default FW_THR_LND_MAX 0

param set-default FW_L1_PERIOD 50

param set-default FW_MAN_P_MAX 30

param set-default FW_PR_P 0.150
param set-default FW_PR_I 0.050
param set-default FW_PR_FF 0.0
param set-default FW_PSP_OFF 2
param set-default FW_P_LIM_MAX 90
param set-default FW_P_LIM_MIN -15
param set-default FW_P_RMAX_NEG 20
param set-default FW_P_RMAX_POS 20
param set-default FW_P_TC 1.0

param set-default FW_RR_FF 0.0
param set-default FW_RR_P 10
param set-default FW_RR_I 0.100
param set-default FW_R_LIM 5
param set-default FW_R_RMAX 5
param set-default FW_R_TC 0.02

param set-default FW_YR_FF 0.0
param set-default FW_YR_P 0.05
param set-default FW_YR_I 0.04
param set-default FW_Y_RMAX 40
param set-default FW_Y_TC 2

param set-default FW_THR_MAX 100
param set-default FW_THR_MIN 100
param set-default FW_THR_CRUISE 100
param set-default FW_SERVICE_CEIL -1
#TECS parameter
param set-default FW_T_CLMB_MAX 1000
param set-default FW_T_SINK_MAX 500
param set-default FW_T_SINK_MIN 1


param set-default FW_W_EN 1

param set-default RTL_DESCEND_ALT 100000
param set-default RTL_RETURN_ALT 100000
param set-default MIS_LTRMIN_ALT 30
param set-default MIS_TAKEOFF_ALT 30

param set-default NAV_ACC_RAD 15
param set-default NAV_DLL_ACT 2

param set-default RWTO_TKOFF 1

#param set-default SYS_CTRL_ALLOC 1
param set-default CA_AIRFRAME 1

param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_PX 0.3

param set-default CA_SV_CS_COUNT 6
#RCS
param set-default CA_SV_CS1_TRQ_R 1
param set-default CA_SV_CS1_TYPE 2
#TVC pitch
param set-default CA_SV_CS2_TRQ_P 1.0
param set-default CA_SV_CS2_TYPE 3
#TVC yaw
param set-default CA_SV_CS3_TRQ_Y 1.0
param set-default CA_SV_CS3_TYPE 4
param set-default CA_SV_CS4_TYPE 9
param set-default CA_SV_CS5_TYPE 10
param set-default PWM_MAIN_FUNC3 204
param set-default PWM_MAIN_FUNC4 205
param set-default PWM_MAIN_FUNC5 101
param set-default PWM_MAIN_FUNC6 201
param set-default PWM_MAIN_FUNC7 202
param set-default PWM_MAIN_FUNC8 203
param set-default PWM_MAIN_FUNC9 206
param set-default PWM_MAIN_REV 256


set MIXER_FILE etc/mixers-sitl/plane_sitl.main.mix
set MIXER custom
